# serve/Dockerfile.serve
FROM python:3.10-slim

WORKDIR /app
COPY requirements-serve.txt .
RUN pip install --no-cache-dir -r requirements-serve.txt

COPY app.py .
COPY entrypoint.sh .

EXPOSE 8000
CMD ["./entrypoint.sh"]

