name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        cd W5-D1-CICD
        pip install -r requirements.txt

    - name: Run training
      run: |
        cd W5-D1-CICD/
        python train.py

    - name: Run tests
      run: |
        cd W5-D1-CICD
        pytest -v

